# Generated by Django 3.2.16 on 2022-12-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0002_alter_material_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(default='Заголовок', max_length=200, verbose_name='Заголовок материала'),
        ),
    ]
