# Generated by Django 3.2.16 on 2022-12-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0003_material_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('pub_date',), 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
    ]
