# Generated by Django 3.2.16 on 2022-12-18 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0004_auto_20221218_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Материал, к которому будут относиться вопросы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='learning_materials.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='material',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Группа, к которой будет относиться материал', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='learning_materials.group', verbose_name='Группа'),
        ),
    ]
