# Generated by Django 3.2.16 on 2022-12-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0005_auto_20221218_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Материал, к которому будут относиться вопросы', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning_materials.material', verbose_name='Материал'),
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст ответа', verbose_name='Текст ответа')),
                ('question', models.ForeignKey(help_text='Вопрос, на который будет дан ответ', on_delete=django.db.models.deletion.CASCADE, related_name='answerws', to='learning_materials.question', verbose_name='Ответ к вопросу')),
            ],
        ),
    ]
